version: '3'

vars:
  PATTERNS:
    sh: find ./tests/ -mindepth 1 -maxdepth 1 -type d -name pattern-*

tasks:

  install:
    cmds:
    - rm -rf build
    - rm -rf eoap-cwlwrap.egg-info
    - pip install -e .

  execute:
    cmds:
    - cmd: |
        set
        eoap-cwlwrap \
        --stage-in ./tests/templates/stage-in.cwl \
        --workflow {{.PATTERN}}/workflow.cwl \
        --workflow-id $( basename {{.PATTERN}} ) \
        --stage-out ./tests/templates/stage-out.cwl \
        --output {{.PATTERN}}/current.cwl \
        --puml
      ignore_error: true
    - cmd: cwltool --validate {{.PATTERN}}/current.cwl
      ignore_error: true
    - cmd: cwltool --print-dot {{.PATTERN}}/current.cwl | dot -Tpng -o {{.PATTERN}}/current.png
      ignore_error: true

  default:
    deps:
    - install
    cmds:
    - for:
        var: PATTERNS
        as: PATTERN
      task: execute
      vars:
        PATTERN: "{{.PATTERN}}"
    - echo "All patterns processed (failures were ignored)"
