version: '3'

vars:
  PATTERNS:
    sh: find ./tests/ -mindepth 1 -maxdepth 1 -type d -name pattern-*

tasks:

  plantuml_install:
    internal: true
    status:
    - command -v plantuml
    cmds:
    - sudo bash -c "curl -L https://raw.githubusercontent.com/riboseinc/plantuml-install/main/ubuntu.sh | bash"

  install:
    cmds:
    - rm -rf build
    - rm -rf eoap-cwlwrap.egg-info
    - pip install -e .

  execute:
    deps:
    - task: plantuml_install
    cmds:
    - cmd: |
        set
        eoap-cwlwrap \
        --stage-in ./tests/templates/stage-in.cwl \
        --workflow {{.PATTERN}}/workflow.cwl \
        --workflow-id $( basename {{.PATTERN}} ) \
        --stage-out ./tests/templates/stage-out.cwl \
        --output {{.PATTERN}}/current.cwl \
        --puml
    - cmd: cwltool --validate {{.PATTERN}}/current.cwl
    - plantuml -tsvg -o ../../docs/diagrams/$(basename "{{.PATTERN}}") {{.PATTERN}}
    - cmd: cwltool --print-dot {{.PATTERN}}/current.cwl | dot -Tsvg -o ./docs/diagrams/$(basename "{{.PATTERN}}")/workflow.svg

  default:
    deps:
    - install
    cmds:
    - for:
        var: PATTERNS
        as: PATTERN
      task: execute
      vars:
        PATTERN: "{{.PATTERN}}"
    - echo "All patterns processed"
