version: '3'

tasks:

  default:
    cmds:
    - rm -rf build
    - rm -rf cwl_chain_builder.egg-info
    - pip install --force-reinstall --user .

  expected:
    cmds:
    - cwltool --pack expected/temp.cwl | yq -P 