version: '3'

vars:
  PATTERNS:
    sh: find ./tests/ -mindepth 1 -maxdepth 1 -type d

tasks:

  install:
    cmds:
    - rm -rf build
    - rm -rf eoap-cwlwrap.egg-info
    - pip install -e .

  execute:
    cmds:
    - |
      eoap-cwlwrap \
      --stage-in {{.PATTERN}}/stage-in.cwl \
      --workflow {{.PATTERN}}/workflow.cwl \
      --workflow-id water-bodies-detection \
      --stage-out {{.PATTERN}}/stage-out.cwl \
      --output {{.PATTERN}}/current.cwl \
      --puml
    - cwltool --validate {{.PATTERN}}/current.cwl

  default:
    deps:
    - install
    cmds:
    - for:
        var: PATTERNS
        as: PATTERN
      task: execute
      vars:
        PATTERN: "{{.PATTERN}}"
